version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gaprc_postgres
    restart: always
    # On dit à Docker de lire le fichier .env
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

volumes:
  pgdata: