# gaprc-frontend/nginx.conf
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Redirige toutes les routes vers index.html (Vital pour React Router)
        try_files $uri $uri/ /index.html;
    }
}